### ISSUE TITLE
PII scraping example not working

### ISSUE THREAD

**Issue by omnibs** [honeycombio/beeline-ruby#138]
The docs show:

```ruby
      # remove potential PII from the active record events
      fields.delete("sql.active_record.binds")
      fields.delete("sql.active_record.type_casted_binds")```
```

But those fields are always empty. PII is showing up in the `sql.active_record.sql` field like:

```sql
INSERT INTO `super_secret_table` (`some_serious_pii`) values ("the serious PII")
```

Is this a bug? Is the example wrong?

```
honeycomb-beeline (2.3.0)
libhoney (1.17.0)
```

**Comment by omnibs** [comment]
Comparing to what `newrelic-rpm` does, I think you need to manually obfuscate queries.

**Comment by ajvondrak** [comment]
Yeah, it looks like NewRelic goes through extra implementation efforts to obfuscate all outgoing SQL statements: https://github.com/newrelic/newrelic-ruby-agent/blob/c36197384754172840547a73b6d51c97a158559d/lib/new_relic/agent/database.rb#L200-L211

The beeline just uses whatever values activerecord is giving with its `ActiveSupport::Notifications` [instrumentation](https://github.com/rails/rails/blob/227a728744ae95ac3ac89fb584e4084a4d53e693/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb#L686-L701). In general, activerecord **should** be using [prepared statements](https://en.wikipedia.org/wiki/Prepared_statement) as much as possible, so the idea of scrubbing out the bind variables is generally cromulent. But there's nothing to stop your app (or some library) from running raw SQL statements that don't make use of bind variables. It can be subtle, depending on the way you invoke certain activerecord methods (e.g., examples in [this post](https://blog.saeloun.com/2019/10/28/bind-parameters-in-activerecord-sql-queries.html)).

Curious where you're getting these unsanitized `INSERT` statements from Rails. Because that might indicate a [security risk](https://stackoverflow.com/questions/8263371/how-can-prepared-statements-protect-from-sql-injection-attacks) for your whole app. 🧐

**Comment by omnibs** [comment]
The application in question is a Rails 5.2 app and the query is a pretty vanilla AR `create` statement:

```ruby
user.some_relation.create({name: 'helo', last_name: 'frend'})
```

Prepared statements are [disabled by default for `Mysql2Adapter`](https://github.com/rails/rails/blob/9fcaac6fb9a391046019a2399b6ede75a002e4c8/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb#L51).

I think it's safe to assume many people will have prepared statements disabled, and better to either make this requirement explicit in the sample obfuscator generated by beeline-ruby, or add scrubbing logic to it.

**Comment by ajvondrak** [comment]
> Prepared statements are [disabled by default for `Mysql2Adapter`](https://github.com/rails/rails/blob/9fcaac6fb9a391046019a2399b6ede75a002e4c8/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb#L51).

Oh, dang! Mystery solved. 😅 Looks like it was disabled by default in https://github.com/rails/rails/commit/846832ae54f93a480f37a14a10874767a6330086 some 4 years ago with no further fanfare, despite mentioning that enabling it by default is probably fine. 😬 Although it seems they were just juggling around some build failures that had to do with disabling prepared statements (cf. https://github.com/rails/rails/commit/2eaa7be638854ec513be4966f526f2564aecb7dd). Accident of history? Because adapters in general have [prepared statements enabled by default](https://github.com/rails/rails/blob/9fcaac6fb9a391046019a2399b6ede75a002e4c8/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb#L98).

> add scrubbing logic to the library

That's for sure the safest thing to do, of course. E.g., still always possible to do a `find_by_sql` anyway. Probably easy to crib off of NewRelic's [implementation](https://github.com/newrelic/newrelic-ruby-agent/blob/c36197384754172840547a73b6d51c97a158559d/lib/new_relic/agent/database/obfuscation_helpers.rb), which is under the Apache 2.0 license (like the beeline).

**Comment by ajvondrak** [comment]
Hey, I have an idea! What if instead of everyone having to copy around their different regular expressions, we could just factor the concern out of both New Relic *and* Honeycomb? [What could go wrong?](https://xkcd.com/927/)

So anyway, I took the New Relic regexes, reworked them to my liking, and packaged them all up into a simple gem. I present to you: [Squelch](https://github.com/ajvondrak/squelch/)!

The obvious problem is that a project as big as New Relic is _way_ more likely to receive updates than my podunk little gem (unless they started using Squelch themselves - wouldn't that be something?). But the advantage is that you can drop it into anywhere else, including your Honeycomb presend hook! 😄

So @omnibs, maybe something like this would be useful for you:

```ruby
begin
  sql = fields["sql.active_record.sql"]
  fields["sql.active_record.sql"] = Squelch.obfuscate!(sql, db: :mysql)
rescue Squelch::Error => e
  fields["sql.active_record.sql"] = "?"
  fields["squelch.error"] = e.class.name
  fields["squelch.error_detail"] = e.message
end
```

And if Honeycomb wants to start rolling this into the beeline? They could just have a dependency on Squelch. 🌈 ✨

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
