### ISSUE TITLE
Builtin rails integration hits rate limits on application boot

### ISSUE THREAD

**Issue by DanielHeath** [honeycombio/beeline-ruby#139]
One of the more common rails deployment patterns is to run a worker pool on each application server.

For instance, we run 8 workers * 6 nodes = 48 new processes starting during a deployment.

During boot, 40 or so events get fired as each worker checks the application schema.

This results in ~2000 events being sent in the same second, which triggers rate-limiting on the honeycomb side.

For now I have worked around this by sampling 0% of spans until 20 seconds has passed, to allow all initialization to finish.

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
