### ISSUE TITLE
[Feature request] ActiveJob integration for rails apps

### ISSUE THREAD

**Issue by DanielHeath** [honeycombio/beeline-ruby#140]
It's common in Rails apps for an interactive HTTP request to spawn one or more background tasks via ActiveJob.

I've had a bit of a look at [the docs](https://www.honeycomb.io/blog/tracing-and-observability-for-background-jobs/); they give a useful starting point for linking spans, but remain a bit "draw the rest of the owl" while lacking images/screencast of what you'll practically gain by doing it.

Given ActiveJob has been a first-class citizen of rails for a few versions now, I'd be interested in seeing the jobs (& stats) get linked to the request that created them (so you could e.g. drill into how long it takes for a job to complete after a user triggers it).

**Comment by martin308** [comment]
@DanielHeath have you tried adding some more active support events to see if it produces any useful information?

You can add additional active support events in the beeline config like [here](https://github.com/honeycombio/beeline-ruby/blob/main/lib/generators/honeycomb/honeycomb_generator.rb#L39)

List of events you can subscribe to [here](https://guides.rubyonrails.org/active_support_instrumentation.html#active-job) 

This might get you most of the way there 🤞

**Comment by DanielHeath** [comment]
I've got there for my specific install using honeykiq, but that assumes a particular background-job library (sidekiq).

Getting trace linking to work would be the main thing that's missing.

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
