### ISSUE TITLE
Conflict with PaperClip

### ISSUE THREAD

**Issue by OAbubakr** [honeycombio/beeline-ruby#144]
Hi, 

Once I added the gem to my gem file and installed it. I got the following error when I start rails console:
` method_missing': undefined method has_attached_file' for #<Class:0x00007f2f938e7d98> (NoMethodError) `
rails (4.2.11.3)
paperclip (4.2.0)
honeycomb-beeline (2.4.0)

Any idea why is this happening?

Thanks you :pray:

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
