### ISSUE TITLE
Keeping a changelog

### ISSUE THREAD

**Issue by DanielHeath** [honeycombio/beeline-ruby#21]
This gem publishes updates frequently, and I feel the need to understand what I'm adding to my codebase rather than blindly updating.

Is there a place I can get a 'whats new' that covers all the honeycomb-authored rubygems when they are released, so I can understand how I should expect these changes will impact me?

**Comment by martin308** [comment]
I've been documenting all of the releases in each of the GitHub releases, you can see the changes in this gem here https://github.com/honeycombio/beeline-ruby/releases. I think you are after the changes across all of the honeycomb gems though right?

I've been working on a new version that incorporates everything into one gem (this one) so that everything is not spread across so many repos. It should be ready for alpha testing soon!

**Comment by martin308** [comment]
@DanielHeath `v1.0.0` has been released now which consolidates all of the ruby support into this repository. Let me know if you think that using GitHub releases is not satisfactory and we can revisit this
