### ISSUE TITLE
Can't use a different client from worker threads

### ISSUE THREAD

**Issue by DanielHeath** [honeycombio/beeline-ruby#23]
It'd be nice to send anything done in a background thread to a different dataset, to make querying easier. Right now I have HTTP and background jobs mixed together, which isn't ideal.

**Comment by martin308** [comment]
@DanielHeath are these actual background threads you are using or a background job like Sidekiq etc?

**Comment by DanielHeath** [comment]
Threads. It'd be easy if it were a separate process.

**Comment by martin308** [comment]
@DanielHeath Hmm I see. I'm guessing you would want to create a new trace then when you create the thread and not propagate any existing traces? Do you have any code samples you can show when you would want to do this?

**Comment by DanielHeath** [comment]
`ActiveJob::QueueAdapters::AsyncAdapter` in rails uses threads this way.

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
