### ISSUE TITLE
Expensive data enrichment in presend hook

### ISSUE THREAD

**Issue by DanielHeath** [honeycombio/beeline-ruby#52]
I'm collecting remote IP addresses, and would like to also lookup the owner (to help go after single-cloud bot operators). 

However, even using RDAP for lookups and caching, there's still a considerable amount of latency (and possible failures).

Is there a straightforward way to do this enrichment outside the main request/response cycle?

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
